version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - dbconfig.env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true

volumes:
  database-data:
